#!/bin/bash

# We assume that /media has nothing mounted on it by the specific key ID we're
# using

BLEEMSYNC_EXEC=/media/bleemsync/bin/execute
LOLHACK_EXEC=/media/lolhack/lolhack.sh

# Fix permission when building from Windows...
chmod +x mount.exfat-fuse

# For each USB drive with the label "SONYXF"
blkid | grep "/dev/sd.1:.*LABEL=\"SONYXF\"" | cut -d: -f1 | while read -r DEV; do
    # Attempt to mount
    echo "Mounting ${DEV}"
    mount ${DEV} /media || continue
    # Verify this is the same drive we launched the package from
    if [ -d "/media/$(basename $(dirname ${PWD}))" ]; then
        # Unmount, then remount the exFAT partition
        echo "Unmounting /media"
        umount /media || break
        echo "Mounting exFAT partition"
        ./mount.exfat-fuse ${DEV%1}2 /media || continue

        pushd
        # Load up BleemSync bootstrap or lolhack script
        if [ -f ${LOLHACK_EXEC} ]; then
            echo "Found lolhack"
            chmod +x ${LOLHACK_EXEC}
            cd $(dirname ${LOLHACK_EXEC})
            ./$(basename ${LOLHACK_EXEC})
        elif [ -f ${BLEEMSYNC_EXEC} ]; then
            echo "Found BleemSync exec"
            chmod +x ${BLEEMSYNC_EXEC}
            ${BLEEMSYNC_EXEC}
        fi
        popd

        # Unmount and finish
        echo "Done; Unmounting /media"
        umount /media
        break
    else
        # Unmount and try any other drives
        echo "Failed to find \"$(basename $(dirname ${PWD}))\" on ${DEV}"
        umount /media
    fi
done
