#!/bin/bash

# We assume that /media has nothing mounted on it by the specific key ID we're
# using

BLEEMSYNC_EXEC=/media/bleemsync/bin/execute
LOLHACK_EXEC=/media/lolhack/lolhack.sh

# For each USB drive with the label "SONYXF"
blkid | grep "/dev/sd.1:.*LABEL=\"SONYXF\"" | cut -d: -f1 | while read -r DEV; do
    # Attempt to mount
    mount ${DEV} /media || continue
    # Verify this is the same drive we launched the package from
    if [ -d "/media/$(basename ${PWD})" ]; then
        # Unmount, then remount the exFAT partition
        umount /media || break
        ./mount.exfat-fuse ${DEV%1}2 /media || continue

        # Load up BleemSync bootstrap or lolhack script
        if [ -f ${LOLHACK_EXEC} ]; then
            chmod +x ${LOLHACK_EXEC}
            cd $(dirname ${LOLHACK_EXEC})
            ./$(basename ${LOLHACK_EXEC})
            cd -
        elif [ -f ${BLEEMSYNC_EXEC} ]; then
            chmod +x ${BLEEMSYNC_EXEC}
            ${BLEEMSYNC_EXEC}
        fi

        # Unmount and finish
        umount /media
        break
    else
        # Unmount and try any other drives
        umount /media
    fi
done
